describe('challenge 5', () => {
    beforeEach(() => {
            cy.login('standard_user', 'secret_sauce')
          })

        it('tc1 error with no data', () => {
          cy.get("[id='shopping_cart_container']").click().end().get("[data-test='checkout']").click()
          cy.get("[data-test='continue']").click()
          cy.get("[data-test='error']").should('have.text', 'Error: First Name is required')
})
        it('tc2 successful shopping flow', ()=> {
            cy.get("[class='shopping_cart_badge']").should('not.exist')
            cy.get("[data-test='add-to-cart-sauce-labs-backpack']").click()
            cy.get("[class='shopping_cart_badge']").should('be.visible')
            cy.get("[id='shopping_cart_container']").click()
            cy.get("[class='cart_list']").should('contain', '1').and('contain', '$29.99').and('contain','Sauce Labs Backpack')
            cy.get("[data-test='remove-sauce-labs-backpack']").should('be.visible')
            cy.get("[data-test='continue-shopping']").should('be.visible')
            cy.get("[data-test='checkout']").should('be.visible')
            cy.get("[data-test='checkout']").click()
            cy.get("[data-test='firstName']").type('Marija')
            cy.get("[data-test='lastName']").type('Matavulj')
            cy.get("[data-test='postalCode']").type('11000')
            cy.get("[data-test='continue']").click()
            cy.get("[class='inventory_item_name']").should('contain','Sauce Labs Backpack')
            cy.get("[data-test='finish']").click()
            cy.get("[id='checkout_complete_container']").should('contain','Thank you for your order').and('be.visible')
            cy.url().should('include', '/checkout-complete.html')
            cy.get("[data-test='back-to-products']").should('be.visible').click()
            cy.url().should('eq', 'https://www.saucedemo.com/inventory.html')
            cy.get("[class='shopping_cart_badge']").should('not.exist')
        })
        it('tc3 removing items from bag', () => {
            cy.get("[data-test='add-to-cart-sauce-labs-bike-light']").click()
            cy.get("[class='shopping_cart_badge']").should('be.visible')
            cy.get("[id='shopping_cart_container']").click()
            cy.get("[id='remove-sauce-labs-bike-light']").click()
            cy.get("[class='shopping_cart_badge']").should('not.exist')
        })
        it('tc4 continue shopping', () => {
            cy.get("[data-test='add-to-cart-sauce-labs-bike-light']").click()
            cy.get("[id='shopping_cart_container']").click()
            cy.get("[data-test='continue-shopping']").click()
            cy.url().should('eq', 'https://www.saucedemo.com/inventory.html')
            cy.get("[class='shopping_cart_badge']").should('be.visible')
        })
    
    })
